services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - DB_HOST=postgres
      - ZEEBE_CLIENT_ID=<your-client-id>
      - ZEEBE_CLIENT_SECRET=<your-client-secret>
      - ZEEBE_ADDRESS=<your-zeebe-address>
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: